name: Generate

on:
  schedule:
    - cron: '55 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Generate Currencies list
        run: npm run currencies
      - name: Generate Crypto symbols list
        run: npm run symbols
      - name: Generate Crypto pricing list
        run: npm run generate
      - name: Generate regular CSV versions
        run: npm run csv
      - name: Generate light CSV versions
        run: npm run csv-light
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit generated data files
