name: Generate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.5'
      - run: npm install
      - run: npm run generate
      - name: Generate CSV versions
        run: npm run csv
        run: npm run csv-light
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit generated data files
